import streamlit as st
import requests
import os

# -----------------------------
# Page Config
# -----------------------------
st.set_page_config(
    page_title="Regulatory Compliance Assistant",
    layout="wide"
)

# -----------------------------
# Backend URL (safe fallback)
# -----------------------------
BACKEND_URL = (
    os.environ.get("BACKEND_URL")
    or st.secrets.get("BACKEND_URL", "http://192.168.144.186:7860/")
)

# -----------------------------
# Title
# -----------------------------
st.title("📜 Regulatory Compliance Assistant")
st.write("Upload regulatory documents and ask compliance-related questions.")

# ======================================================
# SECTION 1 — DOCUMENT UPLOAD & SETTINGS
# ======================================================
st.header("📂 Upload Document")

uploaded_file = st.file_uploader(
    "Upload a PDF document",
    type=["pdf"]
)

with st.expander("⚙️ Document Processing Settings"):
    chunk_size = st.number_input(
        "Chunk size",
        min_value=200,
        max_value=2000,
        value=500,
        step=100
    )

    chunk_overlap = st.number_input(
        "Chunk overlap",
        min_value=0,
        max_value=500,
        value=100,
        step=50
    )

    top_k = st.slider(
        "Number of chunks to retrieve (Top-K)",
        min_value=1,
        max_value=10,
        value=4
    )

upload_btn = st.button("📤 Upload & Index Document")

if upload_btn:
    if uploaded_file is None:
        st.warning("Please upload a PDF document.")
    else:
        with st.spinner("Uploading and indexing document..."):
            try:
                files = {
                    "file": (uploaded_file.name, uploaded_file, "application/pdf")
                }

                data = {
                    "chunk_size": chunk_size,
                    "chunk_overlap": chunk_overlap,
                    "top_k": top_k
                }

                response = requests.post(
                    f"{BACKEND_URL}/upload",
                    files=files,
                    data=data,
                    timeout=300
                )

                if response.status_code == 200:
                    st.success("✅ Document uploaded and indexed successfully.")
                else:
                    st.error("❌ Failed to process document.")

            except requests.exceptions.RequestException as e:
                st.error("❌ Could not connect to backend.")
                st.caption(str(e))
# ======================================================
# SECTION 2 — QUESTION ANSWERING
# ======================================================
st.header("❓ Ask a Question")

question = st.text_input(
    "Enter your question",
    placeholder="e.g., What are the age requirements mentioned in the document?"
)

ask_btn = st.button("🔍 Get Answer")

if ask_btn and question.strip():
    with st.spinner("Generating answer..."):
        try:
            response = requests.post(
                f"{BACKEND_URL}/query",
                json={"question": question},
                timeout=120
            )

            if response.status_code != 200:
                st.error("❌ Backend error while answering the question.")
            else:
                result = response.json()
                with st.expander("🛠 Debug: Raw backend response"):
                    st.json(result)


                # -----------------------------
                # Resolve answer priority
                # -----------------------------
                answer = (
                    result.get("final_answer")
                    or result.get("cited_answer")
                    or result.get("raw_answer")
                )

                st.subheader("✅ Answer")

                if answer:
                    st.write(answer)
                else:
                    st.warning("No answer generated by the model.")

                # -----------------------------
                # Sources (optional)
                # -----------------------------
                sources = result.get("sources", [])
                if sources:
                    with st.expander("📎 Source Documents"):
                        for i, src in enumerate(sources, 1):
                            meta = src.get("metadata", {})
                            st.markdown(
                                f"**{i}. {meta.get('title', 'Unknown document')}**  \n"
                                f"`Chunk ID:` {meta.get('chunk_id', 'N/A')}  \n"
                                f"`Score:` {meta.get('score', 'N/A')}"
                            )

        except requests.exceptions.RequestException as e:
            st.error("❌ Could not connect to backend.")
            st.caption(str(e))

# ======================================================
# Footer
# ======================================================
st.markdown("---")
st.caption("Powered by Gemini Pro · LangChain · FAISS · Streamlit")
